# 1. MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_milk_tea?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# 2. Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jackson.serialization.write_dates_as_timestamps=false